// <auto-generated />
using System;
using DirectiveDrift.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DirectiveDrift.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260810014342_P9Mastery")]
    partial class P9Mastery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("DirectiveDrift.Persistence.BuildEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LatestVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MissionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.BuildVersionEntity", b =>
                {
                    b.Property<string>("BuildId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBeenUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildId", "Version");

                    b.ToTable("BuildVersions");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.CertificationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificationVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionContentVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("BuildId", "BuildVersion");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.CertificationRunEntity", b =>
                {
                    b.Property<string>("CertificationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.HasKey("CertificationId", "RunId");

                    b.HasIndex("RunId");

                    b.HasIndex("CertificationId", "Slot")
                        .IsUnique();

                    b.ToTable("CertificationRuns");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.DecisionRecordEntity", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RunId", "Turn", "AgentId");

                    b.ToTable("DecisionRecords");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.DomainEventEntity", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.HasKey("RunId", "Sequence");

                    b.ToTable("DomainEvents");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.GuestProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GuestProfiles");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.ProviderDecisionCheckpointEntity", b =>
                {
                    b.Property<string>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CostMicros")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LatencyMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreDecisionStateHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptTemplateHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperationId", "AgentId");

                    b.ToTable("ProviderDecisionCheckpoints");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.RunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Assisted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MissionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptedPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantDisclosureJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildId", "BuildVersion");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.RunSnapshotEntity", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("StateJson")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("RunId", "Turn");

                    b.ToTable("RunSnapshots");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.SchemaMetadataEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SchemaMetadata");

                    b.HasData(
                        new
                        {
                            Key = "schema-version",
                            Value = "3"
                        });
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.TurnOperationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HeartbeatUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LeaseExpiresAtUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique()
                        .HasFilter("Status IN (0, 1)");

                    b.HasIndex("RunId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("TurnOperations");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.UsageLedgerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActualCostMicros")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservedCostMicros")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("RunId");

                    b.ToTable("UsageLedger");
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.BuildEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.GuestProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.BuildVersionEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.BuildEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.CertificationEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.GuestProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DirectiveDrift.Persistence.BuildVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildId", "BuildVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.CertificationRunEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.CertificationEntity", null)
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DirectiveDrift.Persistence.RunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.DecisionRecordEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.RunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.DomainEventEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.RunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.ProviderDecisionCheckpointEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.TurnOperationEntity", null)
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.RunEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.GuestProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DirectiveDrift.Persistence.BuildVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildId", "BuildVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.RunSnapshotEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.RunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.TurnOperationEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.RunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectiveDrift.Persistence.UsageLedgerEntity", b =>
                {
                    b.HasOne("DirectiveDrift.Persistence.TurnOperationEntity", null)
                        .WithOne()
                        .HasForeignKey("DirectiveDrift.Persistence.UsageLedgerEntity", "OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DirectiveDrift.Persistence.GuestProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DirectiveDrift.Persistence.RunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
